artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://raw.githubusercontent.com/Durgeshsingh12712/Data-All/refs/heads/main/Unified%20Dataset/customer_support_tickets.csv"
  local_data_file: artifacts/data_ingestion/customer_support_tickets.csv
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/customer_support_tickets.csv
  STATUS_FILE: artifacts/data_validation/status.txt